xvector_dim: 192
num_phonemes: 200
speech_vocab_size: 6561
d_model: 384
nhead: 4
num_layers: 6
dim_feedforward: 1536
dropout: 0.1
max_position_embeddings: 4096
phone_dict_path: data/AISHELL-2-95_5/phone_dict.json
token_dir_name: s3tokenizer_v2_25hz
xvector_backend: eresnet2v2
length_pad_margin: 2

